env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
  - name: DOTNET_gcServer
    value: "1"
  - name: DOTNET_gcConcurrent
    value: "1"
  - name: DOTNET_GCConserveMemory
    value: "5"
  - name: DOTNET_GCRetainVM
    value: "0"
  - name: DOTNET_GCHeapHardLimitPercent
    value: "0x28"

service:
  debugPort:
    enabled: true
    value: 84

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "0.5"
    memory: "1Gi"
